import type { Metadata } from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <header id="auth-header">
            <p>welcome to the training app</p>
            <form >
                <button type="submit">Logout</button>
            </form>
        </header>
        <body>{children}</body>
      </html>
    );
}